/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lmsframes;

import com.sun.jdi.connect.spi.Connection;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.io.File;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class historyFrm extends javax.swing.JFrame {

    /**
     * Creates new form historyFrm
     */
    public historyFrm() {
        initComponents();
        tableupdate();
        Image icon = new ImageIcon(this.getClass().getResource("/iconimage.png")).getImage();
        this.setIconImage(icon);
    }

    java.sql.Connection con;
    java.sql.PreparedStatement pst;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main1 = new rojeru_san.complementos.RSButtonHover();
        admin1 = new rojeru_san.complementos.RSButtonHover();
        issue1 = new rojeru_san.complementos.RSButtonHover();
        returnBook1 = new rojeru_san.complementos.RSButtonHover();
        history1 = new rojeru_san.complementos.RSButtonHover();
        logout1 = new rojeru_san.complementos.RSButtonHover();
        main2 = new rojeru_san.complementos.RSButtonHover();
        admin2 = new rojeru_san.complementos.RSButtonHover();
        issue2 = new rojeru_san.complementos.RSButtonHover();
        returnBook2 = new rojeru_san.complementos.RSButtonHover();
        history2 = new rojeru_san.complementos.RSButtonHover();
        logout2 = new rojeru_san.complementos.RSButtonHover();
        admin = new rojeru_san.complementos.RSButtonHover();
        issue = new rojeru_san.complementos.RSButtonHover();
        returnBook = new rojeru_san.complementos.RSButtonHover();
        history = new rojeru_san.complementos.RSButtonHover();
        logout = new rojeru_san.complementos.RSButtonHover();
        main3 = new rojeru_san.complementos.RSButtonHover();
        filtercombobox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        returnedHistoryTable = new rojerusan.RSTableMetro1();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Management System - History");
        setMaximumSize(new java.awt.Dimension(976, 579));
        setMinimumSize(new java.awt.Dimension(976, 579));
        setPreferredSize(new java.awt.Dimension(976, 579));
        getContentPane().setLayout(null);

        main1.setBackground(new java.awt.Color(113, 201, 206));
        main1.setBorder(null);
        main1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-24.png"))); // NOI18N
        main1.setColorHover(new java.awt.Color(166, 227, 233));
        main1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main1ActionPerformed(evt);
            }
        });
        getContentPane().add(main1);
        main1.setBounds(0, 95, 48, 24);

        admin1.setBackground(new java.awt.Color(113, 201, 206));
        admin1.setBorder(null);
        admin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-administrative-tools-24.png"))); // NOI18N
        admin1.setColorHover(new java.awt.Color(166, 227, 233));
        admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin1ActionPerformed(evt);
            }
        });
        getContentPane().add(admin1);
        admin1.setBounds(0, 147, 48, 24);

        issue1.setBackground(new java.awt.Color(113, 201, 206));
        issue1.setBorder(null);
        issue1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-24.png"))); // NOI18N
        issue1.setColorHover(new java.awt.Color(166, 227, 233));
        issue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue1ActionPerformed(evt);
            }
        });
        getContentPane().add(issue1);
        issue1.setBounds(0, 199, 48, 24);

        returnBook1.setBackground(new java.awt.Color(113, 201, 206));
        returnBook1.setBorder(null);
        returnBook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-24.png"))); // NOI18N
        returnBook1.setColorHover(new java.awt.Color(166, 227, 233));
        returnBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook1);
        returnBook1.setBounds(0, 251, 48, 24);

        history1.setBackground(new java.awt.Color(113, 201, 206));
        history1.setBorder(null);
        history1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-history-24.png"))); // NOI18N
        history1.setColorHover(new java.awt.Color(166, 227, 233));
        history1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history1ActionPerformed(evt);
            }
        });
        getContentPane().add(history1);
        history1.setBounds(0, 303, 48, 24);

        logout1.setBackground(new java.awt.Color(113, 201, 206));
        logout1.setBorder(null);
        logout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-24.png"))); // NOI18N
        logout1.setColorHover(new java.awt.Color(166, 227, 233));
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout1ActionPerformed(evt);
            }
        });
        getContentPane().add(logout1);
        logout1.setBounds(0, 456, 48, 24);

        main2.setBackground(new java.awt.Color(113, 201, 206));
        main2.setBorder(null);
        main2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-24.png"))); // NOI18N
        main2.setColorHover(new java.awt.Color(166, 227, 233));
        main2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main2ActionPerformed(evt);
            }
        });
        getContentPane().add(main2);
        main2.setBounds(0, 95, 48, 24);

        admin2.setBackground(new java.awt.Color(113, 201, 206));
        admin2.setBorder(null);
        admin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-administrative-tools-24.png"))); // NOI18N
        admin2.setColorHover(new java.awt.Color(166, 227, 233));
        admin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin2ActionPerformed(evt);
            }
        });
        getContentPane().add(admin2);
        admin2.setBounds(0, 147, 48, 24);

        issue2.setBackground(new java.awt.Color(113, 201, 206));
        issue2.setBorder(null);
        issue2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-24.png"))); // NOI18N
        issue2.setColorHover(new java.awt.Color(166, 227, 233));
        issue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issue2ActionPerformed(evt);
            }
        });
        getContentPane().add(issue2);
        issue2.setBounds(0, 199, 48, 24);

        returnBook2.setBackground(new java.awt.Color(113, 201, 206));
        returnBook2.setBorder(null);
        returnBook2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-24.png"))); // NOI18N
        returnBook2.setColorHover(new java.awt.Color(166, 227, 233));
        returnBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBook2ActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook2);
        returnBook2.setBounds(0, 251, 48, 24);

        history2.setBackground(new java.awt.Color(113, 201, 206));
        history2.setBorder(null);
        history2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-history-24.png"))); // NOI18N
        history2.setColorHover(new java.awt.Color(166, 227, 233));
        history2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                history2ActionPerformed(evt);
            }
        });
        getContentPane().add(history2);
        history2.setBounds(0, 303, 48, 24);

        logout2.setBackground(new java.awt.Color(113, 201, 206));
        logout2.setBorder(null);
        logout2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-24.png"))); // NOI18N
        logout2.setColorHover(new java.awt.Color(166, 227, 233));
        logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout2ActionPerformed(evt);
            }
        });
        getContentPane().add(logout2);
        logout2.setBounds(0, 456, 48, 24);

        admin.setBackground(new java.awt.Color(113, 201, 206));
        admin.setBorder(null);
        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-administrative-tools-24.png"))); // NOI18N
        admin.setText(" ADMIN TOOLS");
        admin.setColorHover(new java.awt.Color(166, 227, 233));
        admin.setColorText(new java.awt.Color(0, 0, 0));
        admin.setColorTextHover(new java.awt.Color(0, 0, 0));
        admin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin);
        admin.setBounds(240, 15, 120, 24);

        issue.setBackground(new java.awt.Color(113, 201, 206));
        issue.setBorder(null);
        issue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-add-24.png"))); // NOI18N
        issue.setText(" ISSUE BOOK");
        issue.setColorHover(new java.awt.Color(166, 227, 233));
        issue.setColorText(new java.awt.Color(0, 0, 0));
        issue.setColorTextHover(new java.awt.Color(0, 0, 0));
        issue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueActionPerformed(evt);
            }
        });
        getContentPane().add(issue);
        issue.setBounds(382, 15, 120, 24);

        returnBook.setBackground(new java.awt.Color(113, 201, 206));
        returnBook.setBorder(null);
        returnBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-return-24.png"))); // NOI18N
        returnBook.setText(" RETURN BOOK");
        returnBook.setColorHover(new java.awt.Color(166, 227, 233));
        returnBook.setColorText(new java.awt.Color(0, 0, 0));
        returnBook.setColorTextHover(new java.awt.Color(0, 0, 0));
        returnBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBookActionPerformed(evt);
            }
        });
        getContentPane().add(returnBook);
        returnBook.setBounds(510, 15, 130, 24);

        history.setBackground(new java.awt.Color(113, 201, 206));
        history.setBorder(null);
        history.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-history-24.png"))); // NOI18N
        history.setText(" HISTORY");
        history.setColorHover(new java.awt.Color(166, 227, 233));
        history.setColorText(new java.awt.Color(0, 0, 0));
        history.setColorTextHover(new java.awt.Color(0, 0, 0));
        history.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        getContentPane().add(history);
        history.setBounds(656, 15, 90, 24);

        logout.setBackground(new java.awt.Color(113, 201, 206));
        logout.setBorder(null);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-logout-24.png"))); // NOI18N
        logout.setText(" LOGOUT");
        logout.setColorHover(new java.awt.Color(166, 227, 233));
        logout.setColorText(new java.awt.Color(0, 0, 0));
        logout.setColorTextHover(new java.awt.Color(0, 0, 0));
        logout.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(852, 15, 80, 24);

        main3.setBackground(new java.awt.Color(113, 201, 206));
        main3.setBorder(null);
        main3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-menu-24.png"))); // NOI18N
        main3.setText(" MAIN MENU");
        main3.setColorHover(new java.awt.Color(166, 227, 233));
        main3.setColorText(new java.awt.Color(0, 0, 0));
        main3.setColorTextHover(new java.awt.Color(0, 0, 0));
        main3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        main3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                main3ActionPerformed(evt);
            }
        });
        getContentPane().add(main3);
        main3.setBounds(118, 15, 100, 24);

        filtercombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960" }));
        filtercombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtercomboboxItemStateChanged(evt);
            }
        });
        filtercombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtercomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(filtercombobox);
        filtercombobox.setBounds(112, 73, 231, 30);

        returnedHistoryTable.setForeground(new java.awt.Color(0, 0, 0));
        returnedHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "FName", "LName", "Book", "Date Issued", "Return Date", "Payment", "Overdue Charge"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returnedHistoryTable.setBackgoundHead(new java.awt.Color(113, 201, 206));
        returnedHistoryTable.setBackgoundHover(new java.awt.Color(166, 227, 233));
        returnedHistoryTable.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        returnedHistoryTable.setColorSecondary(new java.awt.Color(166, 227, 233));
        returnedHistoryTable.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        returnedHistoryTable.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        returnedHistoryTable.setForegroundHead(new java.awt.Color(0, 0, 0));
        returnedHistoryTable.setSelectionBackground(new java.awt.Color(57, 62, 70));
        returnedHistoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnedHistoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(returnedHistoryTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 123, 849, 360);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/bare-History-Frm.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 960, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      public void tableupdate() {

        int c;
        String selectedYear = (String) filtercombobox.getSelectedItem();

        try {
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            String path = new File("src/LibaryManangementSystem_db.accdb").getAbsolutePath();
            con = DriverManager.getConnection("jdbc:ucanaccess://" + path);

            pst = con.prepareStatement("SELECT * FROM TBL_returnedBookList WHERE dateIssued LIKE ? ORDER BY dateIssued");
            pst.setString(1, selectedYear + "%");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel) returnedHistoryTable.getModel();
            dft.setRowCount(0);

            while (rs.next()) {

                Vector v2 = new Vector();
                for (int i = 1; i <= c; i++) {
                    //v2.add(rs.getString("id"));
                    v2.add(rs.getString("firstName"));
                    v2.add(rs.getString("lastName"));
                    v2.add(rs.getString("book"));
                    v2.add(rs.getString("dateIssued"));
                    //v2.add(rs.getString("dueDate"));     
                    //v2.add(rs.getString("daysOfUsage"));
                    v2.add(rs.getString("returnDate"));
                    v2.add(rs.getString("payment"));
                    v2.add(rs.getString("overdueCharge"));

                }
                dft.addRow(v2);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainFrm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(mainFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void main1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main1ActionPerformed
        // TODO add your handling code here:
        mainFrm MainFRM = new mainFrm();
        MainFRM.show();
        dispose();
    }//GEN-LAST:event_main1ActionPerformed

    private void admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin1ActionPerformed
        // TODO add your handling code here:
        adminFrm adminFRM = new adminFrm();
        adminFRM.show();
        dispose();
    }//GEN-LAST:event_admin1ActionPerformed

    private void issue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue1ActionPerformed
        // TODO add your handling code here:
        issueFrm issueFRM = new issueFrm();
        issueFRM.show();
        dispose();
    }//GEN-LAST:event_issue1ActionPerformed

    private void returnBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBook1ActionPerformed
        // TODO add your handling code here:
        returnFrm returnFRM = new returnFrm();
        returnFRM.show();
        dispose();
    }//GEN-LAST:event_returnBook1ActionPerformed

    private void history1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history1ActionPerformed
        // TODO add your handling code here:
        historyFrm historyFRM = new historyFrm();
        historyFRM.show();
        dispose();
    }//GEN-LAST:event_history1ActionPerformed

    private void logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout1ActionPerformed
        // TODO add your handling code here:
        loginFrm loginFRM = new loginFrm();
        loginFRM.show();
        dispose();
    }//GEN-LAST:event_logout1ActionPerformed

    private void main2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main2ActionPerformed
        // TODO add your handling code here:
        mainFrm MainFRM = new mainFrm();
        MainFRM.show();
        dispose();
    }//GEN-LAST:event_main2ActionPerformed

    private void admin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin2ActionPerformed
        // TODO add your handling code here:
        adminFrm adminFRM = new adminFrm();
        adminFRM.show();
        dispose();
    }//GEN-LAST:event_admin2ActionPerformed

    private void issue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issue2ActionPerformed
        // TODO add your handling code here:
        issueFrm issueFRM = new issueFrm();
        issueFRM.show();
        dispose();
    }//GEN-LAST:event_issue2ActionPerformed

    private void returnBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBook2ActionPerformed
        // TODO add your handling code here:
        returnFrm returnFRM = new returnFrm();
        returnFRM.show();
        dispose();
    }//GEN-LAST:event_returnBook2ActionPerformed

    private void history2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_history2ActionPerformed
        // TODO add your handling code here:
        historyFrm historyFRM = new historyFrm();
        historyFRM.show();
        dispose();
    }//GEN-LAST:event_history2ActionPerformed

    private void logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout2ActionPerformed
        // TODO add your handling code here:
        loginFrm loginFRM = new loginFrm();
        loginFRM.show();
        dispose();
    }//GEN-LAST:event_logout2ActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        adminFrm adminFRM = new adminFrm();
        adminFRM.show();
        dispose();
    }//GEN-LAST:event_adminActionPerformed

    private void issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueActionPerformed
        // TODO add your handling code here:
        issueFrm issueFRM = new issueFrm();
        issueFRM.show();
        dispose();
    }//GEN-LAST:event_issueActionPerformed

    private void returnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBookActionPerformed
        // TODO add your handling code here:
        returnFrm returnFRM = new returnFrm();
        returnFRM.show();
        dispose();
    }//GEN-LAST:event_returnBookActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        // TODO add your handling code here:
        historyFrm historyFRM = new historyFrm();
        historyFRM.show();
        dispose();
    }//GEN-LAST:event_historyActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        loginFrm loginFRM = new loginFrm();
        loginFRM.show();
        dispose();
    }//GEN-LAST:event_logoutActionPerformed

    private void main3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_main3ActionPerformed
        // TODO add your handling code here:
        mainFrm MainFRM = new mainFrm();
        MainFRM.show();
        dispose();
    }//GEN-LAST:event_main3ActionPerformed

    private void returnedHistoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnedHistoryTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_returnedHistoryTableMouseClicked

    private void filtercomboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtercomboboxItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            tableupdate();
        }

    }//GEN-LAST:event_filtercomboboxItemStateChanged

    private void filtercomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtercomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtercomboboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(historyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(historyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(historyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(historyFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new historyFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover admin;
    private rojeru_san.complementos.RSButtonHover admin1;
    private rojeru_san.complementos.RSButtonHover admin2;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> filtercombobox;
    private rojeru_san.complementos.RSButtonHover history;
    private rojeru_san.complementos.RSButtonHover history1;
    private rojeru_san.complementos.RSButtonHover history2;
    private rojeru_san.complementos.RSButtonHover issue;
    private rojeru_san.complementos.RSButtonHover issue1;
    private rojeru_san.complementos.RSButtonHover issue2;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.complementos.RSButtonHover logout;
    private rojeru_san.complementos.RSButtonHover logout1;
    private rojeru_san.complementos.RSButtonHover logout2;
    private rojeru_san.complementos.RSButtonHover main1;
    private rojeru_san.complementos.RSButtonHover main2;
    private rojeru_san.complementos.RSButtonHover main3;
    private rojeru_san.complementos.RSButtonHover returnBook;
    private rojeru_san.complementos.RSButtonHover returnBook1;
    private rojeru_san.complementos.RSButtonHover returnBook2;
    private rojerusan.RSTableMetro1 returnedHistoryTable;
    // End of variables declaration//GEN-END:variables
}
